<?php

return [
    'groups' => [
        'Inventory & Items' => [
            'view_inventory' => 'View items list & stock levels',
            'add_items' => 'Register new items',
            'edit_items' => 'Edit existing items',
            'delete_items' => 'Delete items',
            'manage_categories' => 'Manage categories',
            'manage_packaging' => 'Manage packaging & units',
            'view_stock_history' => 'View stock movement history',
        ],
        'Stock Receiving' => [
            'receive_stock' => 'Receive incoming stock',
            'cancel_receiving' => 'Cancel receiving orders',
            'record_stock_loss' => 'Record lost / damaged / destroyed stock',
            'cancel_stock_loss' => 'Cancel stock loss records',
        ],
        'Sales Shifts' => [
            'open_shift' => 'Open & close own sales shift',
            'view_all_shifts' => 'View all staff shifts',
        ],
        'Store / POS' => [
            'process_sales' => 'Process POS sales (place orders)',
            'view_sales_history' => 'View POS sales history & receipts',
            'cancel_sales' => 'Cancel sales',
            'collect_payments' => 'Collect payments on POS sales',
        ],
        'Invoices & Billing' => [
            'view_invoices' => 'View & print invoices',
            'create_invoices' => 'Create new invoices',
            'collect_invoice_payments' => 'Record payments on invoices',
        ],
        'Customers & Credit' => [
            'manage_customers' => 'Manage customer records',
            'manage_debts' => 'Manage customer debts & credit sales',
        ],
        'Daily Reconciliation' => [
            'submit_day_closing' => 'Submit daily reconciliation',
            'verify_day_closing' => 'Verify reconciliation (supervisor)',
            'view_closing_history' => 'View closing history',
            'view_boss_financial_review' => 'View boss financial review on handovers (debt, profit, circulation)',
        ],
        'Reports & Finance' => [
            'view_reports' => 'View master sheet & daily reports',
            'finalize_reports' => 'Finalize daily reports',
            'manage_petty_cash' => 'Manage petty cash & expenses',
        ],
        'Business Setup' => [
            'manage_business_settings' => 'Manage business profile & finance settings',
            'manage_sales_targets' => 'Set sales targets (daily / weekly / monthly)',
            'manage_payment_methods' => 'Configure payment methods',
            'manage_branches' => 'Manage branches',
            'verify_stock_shortages' => 'Verify stock shortage reports',
        ],
        'Administration' => [
            'manage_staff' => 'Manage staff & roles',
            'manage_suppliers' => 'Manage suppliers',
            'manage_support' => 'Access support center',
            'view_audit_logs' => 'View business audit logs',
        ],
    ],

    'presets' => [
        'Cashier' => [
            'open_shift',
            'process_sales',
            'view_sales_history',
            'collect_payments',
            'view_invoices',
            'create_invoices',
            'collect_invoice_payments',
            'manage_customers',
            'submit_day_closing',
            'manage_support',
        ],
        'Store Manager' => [
            'view_inventory',
            'add_items',
            'edit_items',
            'manage_categories',
            'manage_packaging',
            'receive_stock',
            'record_stock_loss',
            'open_shift',
            'view_all_shifts',
            'process_sales',
            'view_sales_history',
            'cancel_sales',
            'collect_payments',
            'view_invoices',
            'create_invoices',
            'collect_invoice_payments',
            'manage_customers',
            'manage_debts',
            'submit_day_closing',
            'verify_day_closing',
            'view_closing_history',
            'view_boss_financial_review',
            'view_reports',
            'manage_support',
        ],
        'Supervisor' => [
            'view_inventory',
            'view_stock_history',
            'view_all_shifts',
            'view_sales_history',
            'view_invoices',
            'manage_debts',
            'verify_day_closing',
            'view_closing_history',
            'view_boss_financial_review',
            'view_reports',
            'verify_stock_shortages',
            'manage_support',
        ],
    ],
];
