<?php

return [
    'owner' => [
        [
            'title' => 'Karibu Mauzo Link',
            'hero' => true,
            'intro' => '<p class="mb-2">Hii ni <strong>Mwongozo Rasmi wa Mfumo</strong> — utaelewa kila sehemu ya dashibodi na menyu.</p><p class="mb-0 text-muted small">Chukua dakika 3–5. Unaweza kuruka na kurudia baadaye kutoka menyu ya <strong>System Guide</strong>.</p>',
        ],
        [
            'element' => '[data-tour="sidebar-profile"]',
            'title' => 'Wasifu Wako',
            'intro' => 'Hapa unaona jina lako na jukumu (role) ndani ya biashara. Hakikisha unaingia kwa akaunti sahihi.',
        ],
        [
            'element' => '[data-tour="menu-dashboard"]',
            'title' => 'Dashboard — Dashibodi',
            'intro' => 'Dashibodi ni ukurasa wa kwanza. Inaonyesha muhtasari wa mauzo, stock, na utendaji wa biashara yako kwa haraka.',
        ],
        [
            'element' => '[data-tour="today-revenue"]',
            'title' => 'Mauzo ya Leo — Today Revenue',
            'intro' => 'Jumla ya mapato yaliyokusanywa <strong>leo</strong> kutoka mauzo yote yaliyofanyika.',
        ],
        [
            'element' => '[data-tour="month-revenue"]',
            'title' => 'Mauzo ya Mwezi — Monthly Revenue',
            'intro' => 'Muhtasari wa mwezi huu: jumla ya mauzo, idadi ya oda, na kiasi kilichokusanywa.',
        ],
        [
            'element' => '[data-tour="stock-alerts"]',
            'title' => 'Tahadhari za Stock — Stock Alerts',
            'intro' => 'Angalia bidhaa zenye uhaba wa stock, shortages zilizoripotiwa, na hali inayohitaji hatua.',
        ],
        [
            'element' => '[data-tour="month-purchases"]',
            'title' => 'Manunuzi ya Mwezi — Month Purchases',
            'intro' => 'Gharama ya stock iliyopokelewa mwezi huu — inasaidia kulinganisha mauzo na ununuzi.',
        ],
        [
            'element' => '[data-tour="sales-targets"]',
            'title' => 'Malengo ya Mauzo — Sales Targets',
            'intro' => 'Fuatilia maendeleo ya malengo ya mauzo ya siku, wiki, au mwezi kwa wafanyakazi na biashara.',
            'plan_feature' => 'sales_targets',
        ],
        [
            'element' => '[data-tour="revenue-chart"]',
            'title' => 'Mwenendo wa Mauzo — Revenue Trend',
            'intro' => 'Chati ya mauzo ya siku 7 zilizopita. Inasaidia kuona mwenendo na siku zenye mauzo makubwa.',
        ],
        [
            'element' => '[data-tour="top-products"]',
            'title' => 'Bidhaa Bora — Top Products',
            'intro' => 'Bidhaa zinazouzwa zaidi mwezi huu kwa idadi na thamani ya mauzo.',
        ],
        [
            'element' => '[data-tour="menu-notes"]',
            'title' => 'Notes & Reminders',
            'intro' => 'Andika vidokezo na weka vikumbusho vya kazi muhimu ndani ya mfumo.',
            'plan_feature' => 'notes_reminders',
        ],
        [
            'element' => '[data-tour="menu-registration"]',
            'title' => 'Registration — Usajili wa Bidhaa',
            'intro' => 'Sajili bidhaa, makundi (categories), packaging, units, na suppliers. Hii ndiyo msingi wa stock na mauzo.',
            'retail_required' => true,
            'any_permissions' => ['view_inventory', 'manage_categories', 'add_items'],
        ],
        [
            'element' => '[data-tour="menu-receiving"]',
            'title' => 'Receiving — Kupokea Stock',
            'intro' => 'Ingiza bidhaa mpya ulizopokea kutoka kwa supplier ili stock iongezeke kwenye mfumo.',
            'retail_required' => true,
            'any_permissions' => ['receive_stock'],
        ],
        [
            'element' => '[data-tour="menu-stock-losses"]',
            'title' => 'Stock Losses — Hasara za Stock',
            'intro' => 'Rekodi bidhaa zilizopotea, kuharibika, au kutotoka kwa mauzo — kwa uwazi na uwajibikaji.',
            'retail_required' => true,
            'any_permissions' => ['record_stock_loss', 'view_stock_history', 'open_shift', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-shifts"]',
            'title' => 'Sales Shifts — Vipindi vya Mauzo',
            'intro' => 'Simamia shift za wafanyakazi: kufungua, kufunga, na kufuatilia shughuli za kila kipindi.',
            'any_permissions' => ['open_shift', 'process_sales', 'view_all_shifts'],
        ],
        [
            'element' => '[data-tour="menu-live-sales"]',
            'title' => 'Live Sales Pulse',
            'intro' => 'Angalia mauzo yanayofanyika <strong>wakati huo huo</strong> — moja kwa moja kutoka duka.',
            'plan_feature' => 'live_sales_pulse',
            'any_permissions' => ['view_reports', 'view_sales_history', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-pos"]',
            'title' => 'Store / POS — Duka',
            'intro' => 'Sehemu ya mauzo ya haraka (Point of Sale). Wateja hununuliwa bidhaa hapa na risiti inatolewa.',
            'retail_required' => true,
            'any_permissions' => ['process_sales', 'view_sales_history'],
        ],
        [
            'element' => '[data-tour="menu-services"]',
            'title' => 'Services — Huduma',
            'intro' => 'Simamia huduma (si bidhaa): usajili, kategoria, mauzo ya huduma, handover, na invoice za huduma.',
            'services_required' => true,
            'any_permissions' => ['process_sales', 'view_sales_history', 'manage_categories', 'view_inventory'],
        ],
        [
            'element' => '[data-tour="menu-invoices"]',
            'title' => 'Invoices — Ankara',
            'intro' => 'Tengeneza, tuma, na fuatilia invoice kwa wateja — pamoja na hali ya malipo.',
            'plan_feature' => 'invoices',
            'any_permissions' => ['view_invoices', 'create_invoices', 'collect_invoice_payments', 'process_sales', 'view_sales_history'],
        ],
        [
            'element' => '[data-tour="menu-debts"]',
            'title' => 'Debts — Deni',
            'intro' => 'Fuatilia deni la wateja: salio linalodaiwa na historia ya marejesho.',
            'plan_feature' => 'debts',
            'any_permissions' => ['manage_debts', 'process_sales', 'collect_payments'],
        ],
        [
            'element' => '[data-tour="menu-customers"]',
            'title' => 'Customers — Wateja',
            'intro' => 'Orodha ya wateja wako — majina, nambari, na historia ya ununuzi.',
            'plan_feature' => 'customers',
            'any_permissions' => ['manage_customers'],
        ],
        [
            'element' => '[data-tour="menu-customer-comms"]',
            'title' => 'Customer Comms — Mawasiliano',
            'intro' => 'Tuma SMS au arifa kwa wateja — invoice, vikumbusho vya deni, na mengineyo.',
            'plan_feature' => 'customer_communication',
            'any_permissions' => ['manage_customers'],
        ],
        [
            'element' => '[data-tour="menu-staff"]',
            'title' => 'Staff Management — Wafanyakazi',
            'intro' => 'Ongeza wafanyakazi, weka majukumu (roles), na dhibiti nani anaweza kufanya nini.',
            'any_permissions' => ['manage_staff'],
        ],
        [
            'element' => '[data-tour="menu-day-closing"]',
            'title' => 'Daily Reconciliation — Ufuatiliaji wa Siku',
            'intro' => 'Funga siku kwa kuhesabu pesa, stock, na kuwasilisha ripoti ya mwisho wa siku (day closing).',
            'any_permissions' => ['submit_day_closing', 'verify_day_closing', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-money-shorts"]',
            'title' => 'Money Shorts — Upungufu wa Pesa',
            'intro' => 'Fuatilia na simamia upungufu wa pesa kutoka kwa shift na day closing.',
            'role' => 'owner',
            'any_permissions' => ['submit_day_closing', 'verify_day_closing', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-stock-shortages"]',
            'title' => 'Stock Shortages — Upungufu wa Stock',
            'intro' => 'Angalia na thibitisha shortages zilizogunduliwa wakati wa stock check au shift.',
            'any_permissions' => ['verify_stock_shortages', 'view_reports'],
        ],
        [
            'element' => '[data-tour="menu-reports"]',
            'title' => 'Reports — Ripoti',
            'intro' => 'Ripoti kamili: mauzo ya kila siku, faida, deni, bidhaa, gharama, circulation vs profit, na master sheet.',
            'plan_features' => ['reports_daily', 'reports_expenses', 'reports_sales', 'reports_products', 'reports_debts', 'reports_profit', 'reports_circulation', 'master_sheet'],
            'any_permissions' => ['view_reports', 'verify_day_closing', 'finalize_reports'],
        ],
        [
            'element' => '[data-tour="menu-petty-cash"]',
            'title' => 'Petty Cash — Petty Cash',
            'intro' => 'Simamia matumizi madogo ya pesa taslimu ndani ya biashara.',
            'plan_feature' => 'petty_cash',
            'any_permissions' => ['manage_petty_cash'],
        ],
        [
            'element' => '[data-tour="menu-closing-history"]',
            'title' => 'Closing History — Historia ya Kufunga Siku',
            'intro' => 'Angalia rekodi za day closing zilizopita kwa ukaguzi na uhakiki.',
            'any_permissions' => ['view_closing_history', 'view_reports', 'verify_day_closing'],
        ],
        [
            'element' => '[data-tour="menu-branches"]',
            'title' => 'Branches — Matawi',
            'intro' => 'Simamia matawi ya biashara yako — ongeza, badilisha, na badilisha kati yao.',
            'plan_feature' => 'branches',
            'any_permissions' => ['manage_branches'],
        ],
        [
            'element' => '[data-tour="menu-sales-targets-nav"]',
            'title' => 'Sales Targets — Malengo ya Mauzo',
            'intro' => 'Weka na simamia malengo ya mauzo kwa wafanyakazi, matawi, au biashara nzima.',
            'plan_feature' => 'sales_targets',
            'any_permissions' => ['manage_business_settings'],
        ],
        [
            'element' => '[data-tour="menu-settings"]',
            'title' => 'Business Settings — Mipangilio',
            'intro' => 'Mipangilio ya biashara: njia za malipo, SMS, automation, na mapendeleo mengine.',
            'any_permissions' => ['manage_business_settings', 'manage_payment_methods'],
        ],
        [
            'element' => '[data-tour="menu-upgrade"]',
            'title' => 'Upgrade Plan — Boresha Kifurushi',
            'intro' => 'Angalia kifurushi chako cha sasa na chaguo za kuboresha ili kupata vipengele zaidi.',
            'any_roles' => ['owner', 'staff'],
        ],
        [
            'element' => '[data-tour="menu-activity-log"]',
            'title' => 'Activity Log — Shughuli za Mfumo',
            'intro' => 'Rekodi ya shughuli muhimu zilizofanyika ndani ya biashara yako kwa uwajibikaji.',
            'any_permissions' => ['view_audit_logs'],
        ],
        [
            'element' => '[data-tour="menu-support"]',
            'title' => 'My Support — Msaada',
            'intro' => 'Wasiliana na timu ya msaada wa Mauzo Link — fungua tiketi na fuatilia majibu.',
        ],
        [
            'element' => '[data-tour="menu-guide"]',
            'title' => 'System Guide — Mwongozo wa Mfumo',
            'intro' => 'Bofya hapa wakati wowote kurudia mwongozo huu.',
        ],
        [
            'title' => 'Hongera — Uko Tayari!',
            'intro' => '<p class="mb-2">Umekamilisha mwongozo wa mfumo. Sasa unaweza kuanza kusimamia biashara yako kwa ufanisi.</p><p class="mb-0"><strong>Hatua inayofuata:</strong> Sajili bidhaa → Pokea stock → Fungua shift → Anza kuuza kwenye POS.</p>',
        ],
    ],

    'sales_officer' => [
        [
            'title' => 'Karibu Mauzo Link',
            'hero' => true,
            'intro' => '<p class="mb-2">Hii ni <strong>Mwongozo Rasmi</strong> kwa wafanyakazi wa mauzo.</p><p class="mb-0 text-muted small">Utaelewa hatua za kufanya kazi kwa usahihi kila siku.</p>',
        ],
        [
            'element' => '[data-tour="sidebar-profile"]',
            'title' => 'Wasifu Wako',
            'intro' => 'Jina lako na jukumu lako ndani ya biashara. Tumia akaunti yako pekee — usishiriki nenosiri.',
        ],
        [
            'element' => '[data-tour="shift-stock-check"]',
            'title' => 'Uhakiki wa Stock — Stock Check',
            'intro' => 'Kabla ya kuuza, hakiki stock halisi kwenye duka. Ingiza idadi halisi ya kila bidhaa kwa usahihi.',
        ],
        [
            'element' => '[data-tour="menu-dashboard"]',
            'title' => 'Dashboard',
            'intro' => 'Muhtasari wa kazi yako: mauzo ya leo, shift, na bidhaa zinazohitaji uhakiki.',
        ],
        [
            'element' => '[data-tour="menu-shifts"]',
            'title' => 'Sales Shifts',
            'intro' => '<strong>Lazima</strong> ufungue shift kabla ya kuuza. Funga shift ukimaliza kazi ya siku.',
            'any_permissions' => ['open_shift', 'process_sales', 'view_all_shifts'],
        ],
        [
            'element' => '[data-tour="menu-pos"]',
            'title' => 'Store / POS',
            'intro' => 'Hapa unafanya mauzo. Chagua bidhaa, idadi, na njia ya malipo — risiti inatolewa moja kwa moja.',
            'retail_required' => true,
            'any_permissions' => ['process_sales'],
        ],
        [
            'element' => '[data-tour="menu-services"]',
            'title' => 'Services POS',
            'intro' => 'Ikiwa biashara inauza huduma, mauzo ya huduma yanafanyika hapa.',
            'services_required' => true,
            'any_permissions' => ['process_sales'],
        ],
        [
            'element' => '[data-tour="menu-invoices"]',
            'title' => 'Invoices',
            'intro' => 'Tengeneza na tuma invoice kwa wateja na fuatilia malipo.',
            'plan_feature' => 'invoices',
            'any_permissions' => ['view_invoices', 'create_invoices', 'collect_invoice_payments', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-debts"]',
            'title' => 'Debts — Deni',
            'intro' => 'Angalia deni la wateja na rekodi marejesho ya sehemu.',
            'plan_feature' => 'debts',
            'any_permissions' => ['manage_debts', 'process_sales', 'collect_payments'],
        ],
        [
            'element' => '[data-tour="menu-customers"]',
            'title' => 'Customers',
            'intro' => 'Tafuta au ongeza taarifa za wateja wakati wa mauzo au deni.',
            'plan_feature' => 'customers',
            'any_permissions' => ['manage_customers'],
        ],
        [
            'element' => '[data-tour="menu-day-closing"]',
            'title' => 'Daily Reconciliation',
            'intro' => 'Mwisho wa siku: wasilisha hesabu ya pesa na stock — day closing / handover.',
            'any_permissions' => ['submit_day_closing', 'verify_day_closing', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-stock-shortages"]',
            'title' => 'Stock Shortages',
            'intro' => 'Angalia shortages zilizogunduliwa wakati wa stock check.',
            'any_permissions' => ['verify_stock_shortages', 'view_reports'],
        ],
        [
            'element' => '[data-tour="menu-support"]',
            'title' => 'My Support',
            'intro' => 'Wasiliana na msaada ikiwa unakumbwa na changamoto.',
        ],
        [
            'element' => '[data-tour="menu-guide"]',
            'title' => 'System Guide',
            'intro' => 'Rudia mwongozo huu wakati wowote.',
        ],
        [
            'title' => 'Uko Tayari Kuanza!',
            'intro' => '<p class="mb-0"><strong>Mtiririko wa kazi:</strong> Hakiki stock → Fungua shift → Uza kwenye POS → Funga siku.</p>',
        ],
    ],

    'staff' => [
        [
            'title' => 'Karibu Mauzo Link',
            'hero' => true,
            'intro' => '<p class="mb-2">Mwongozo huu unaelezea sehemu unazoweza kutumia kulingana na jukumu lako.</p><p class="mb-0 text-muted small">Hatua zisizo kwenye menyu yako hazitajwi — huna ruhusa ya kuzifikia.</p>',
        ],
        [
            'element' => '[data-tour="sidebar-profile"]',
            'title' => 'Wasifu Wako',
            'intro' => 'Jina na jukumu lako. Kazi unazoona zinategemea ruhusa ulizopewa.',
        ],
        [
            'element' => '[data-tour="menu-dashboard"]',
            'title' => 'Dashboard',
            'intro' => 'Muhtasari wa kazi na takwimu unazoidhinishwa kuziona.',
        ],
        [
            'element' => '[data-tour="staff-count"]',
            'title' => 'Wafanyakazi — Staff',
            'intro' => 'Idadi ya wafanyakazi waliosajiliwa kwenye biashara.',
        ],
        [
            'element' => '[data-tour="items-count"]',
            'title' => 'Bidhaa — Items',
            'intro' => 'Jumla ya bidhaa zilizosajiliwa kwenye mfumo.',
        ],
        [
            'element' => '[data-tour="today-sales"]',
            'title' => 'Mauzo ya Leo',
            'intro' => 'Muhtasari wa mauzo ya leo kwenye biashara.',
        ],
        [
            'element' => '[data-tour="menu-notes"]',
            'title' => 'Notes & Reminders',
            'intro' => 'Vidokezo na vikumbusho vya kazi.',
            'plan_feature' => 'notes_reminders',
        ],
        [
            'element' => '[data-tour="menu-registration"]',
            'title' => 'Registration',
            'intro' => 'Usajili wa bidhaa, makundi, na suppliers.',
            'retail_required' => true,
            'any_permissions' => ['view_inventory', 'manage_categories', 'add_items'],
        ],
        [
            'element' => '[data-tour="menu-receiving"]',
            'title' => 'Receiving',
            'intro' => 'Kupokea stock kutoka kwa supplier.',
            'retail_required' => true,
            'any_permissions' => ['receive_stock'],
        ],
        [
            'element' => '[data-tour="menu-stock-losses"]',
            'title' => 'Stock Losses',
            'intro' => 'Rekodi hasara za stock.',
            'retail_required' => true,
            'any_permissions' => ['record_stock_loss', 'view_stock_history'],
        ],
        [
            'element' => '[data-tour="menu-shifts"]',
            'title' => 'Sales Shifts',
            'intro' => 'Simamia vipindi vya mauzo.',
            'any_permissions' => ['open_shift', 'process_sales', 'view_all_shifts'],
        ],
        [
            'element' => '[data-tour="menu-live-sales"]',
            'title' => 'Live Sales Pulse',
            'intro' => 'Mauzo ya moja kwa moja.',
            'plan_feature' => 'live_sales_pulse',
            'any_permissions' => ['view_reports', 'view_sales_history', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-pos"]',
            'title' => 'Store / POS',
            'intro' => 'Mauzo ya bidhaa.',
            'retail_required' => true,
            'any_permissions' => ['process_sales', 'view_sales_history'],
        ],
        [
            'element' => '[data-tour="menu-services"]',
            'title' => 'Services',
            'intro' => 'Mauzo na usimamizi wa huduma.',
            'services_required' => true,
            'any_permissions' => ['process_sales', 'view_sales_history'],
        ],
        [
            'element' => '[data-tour="menu-invoices"]',
            'title' => 'Invoices',
            'intro' => 'Ankara kwa wateja.',
            'plan_feature' => 'invoices',
            'any_permissions' => ['view_invoices', 'create_invoices', 'collect_invoice_payments'],
        ],
        [
            'element' => '[data-tour="menu-debts"]',
            'title' => 'Debts',
            'intro' => 'Deni la wateja.',
            'plan_feature' => 'debts',
            'any_permissions' => ['manage_debts', 'collect_payments'],
        ],
        [
            'element' => '[data-tour="menu-customers"]',
            'title' => 'Customers',
            'intro' => 'Orodha ya wateja.',
            'plan_feature' => 'customers',
            'any_permissions' => ['manage_customers'],
        ],
        [
            'element' => '[data-tour="menu-staff"]',
            'title' => 'Staff Management',
            'intro' => 'Wafanyakazi na majukumu.',
            'any_permissions' => ['manage_staff'],
        ],
        [
            'element' => '[data-tour="menu-day-closing"]',
            'title' => 'Daily Reconciliation',
            'intro' => 'Kufunga siku na handover.',
            'any_permissions' => ['submit_day_closing', 'verify_day_closing', 'process_sales'],
        ],
        [
            'element' => '[data-tour="menu-reports"]',
            'title' => 'Reports',
            'intro' => 'Ripoti za biashara unazoidhinishwa kuziona.',
            'plan_features' => ['reports_daily', 'reports_expenses', 'reports_sales', 'reports_products', 'reports_debts', 'reports_profit', 'reports_circulation', 'master_sheet'],
            'any_permissions' => ['view_reports', 'verify_day_closing', 'finalize_reports'],
        ],
        [
            'element' => '[data-tour="menu-settings"]',
            'title' => 'Business Settings',
            'intro' => 'Mipangilio ya biashara.',
            'any_permissions' => ['manage_business_settings', 'manage_payment_methods'],
        ],
        [
            'element' => '[data-tour="menu-support"]',
            'title' => 'My Support',
            'intro' => 'Msaada wa kiufundi.',
        ],
        [
            'element' => '[data-tour="menu-guide"]',
            'title' => 'System Guide',
            'intro' => 'Rudia mwongozo huu.',
        ],
        [
            'title' => 'Mwongozo Umekamilika',
            'intro' => 'Tumia menyu upande wa kushoto kufikia kazi zako. Kwa msaada zaidi, fungua <strong>My Support</strong>.',
        ],
    ],

    'unassigned' => [
        [
            'title' => 'Karibu Mauzo Link',
            'hero' => true,
            'intro' => '<p class="mb-2">Akaunti yako imesajiliwa kwa mafanikio.</p><p class="mb-0">Bado hujapangiwa <strong>jukumu (role)</strong> na ruhusa za kufanya kazi. Tafadhali wasiliana na mmiliki wa biashara au msimamizi wako.</p>',
        ],
        [
            'element' => '[data-tour="sidebar-profile"]',
            'title' => 'Wasifu Wako',
            'intro' => 'Hapa unaona jina lako. Baada ya kupangiwa jukumu, menyu na dashibodi zitaonekana kulingana na kazi yako.',
        ],
        [
            'element' => '[data-tour="menu-support"]',
            'title' => 'My Support',
            'intro' => 'Unaweza kuwasiliana na timu ya msaada ikiwa unahitaji msaada wa haraka.',
        ],
        [
            'title' => 'Subiri Uwekewe Jukumu',
            'intro' => 'Ukishapangiwa jukumu, ingia tena au onyesha upya ukurasa — mwongozo kamili utaonekana kiotomatiki.',
        ],
    ],
];
