<?php

/**
 * Tanzania regions and districts (mainland + Zanzibar administrative areas).
 */
return [
    'regions' => [
        'Arusha' => [
            'Arusha City',
            'Arusha District',
            'Karatu',
            'Longido',
            'Meru',
            'Monduli',
            'Ngorongoro',
        ],
        'Dar es Salaam' => [
            'Ilala',
            'Kinondoni',
            'Temeke',
            'Ubungo',
            'Kigamboni',
        ],
        'Dodoma' => [
            'Dodoma City',
            'Bahi',
            'Chamwino',
            'Chemba',
            'Kondoa',
            'Kongwa',
            'Mpwapwa',
        ],
        'Geita' => [
            'Geita Town',
            'Geita District',
            'Bukombe',
            'Chato',
            'Mbogwe',
            "Nyang'hwale",
        ],
        'Iringa' => [
            'Iringa Municipal',
            'Iringa District',
            'Kilolo',
            'Mafinga Town',
            'Mufindi',
        ],
        'Kagera' => [
            'Bukoba Municipal',
            'Bukoba District',
            'Biharamulo',
            'Karagwe',
            'Kyerwa',
            'Missenyi',
            'Muleba',
            'Ngara',
        ],
        'Katavi' => [
            'Mpanda Town',
            'Mpanda District',
            'Mlele',
            'Nsimbo',
        ],
        'Kigoma' => [
            'Kigoma-Ujiji Municipal',
            'Kigoma District',
            'Buhigwe',
            'Kakonko',
            'Kasulu Town',
            'Kasulu District',
            'Kibondo',
            'Uvinza',
        ],
        'Kilimanjaro' => [
            'Moshi Municipal',
            'Moshi District',
            'Hai',
            'Mwanga',
            'Rombo',
            'Same',
            'Siha',
        ],
        'Lindi' => [
            'Lindi Municipal',
            'Lindi District',
            'Kilwa',
            'Liwale',
            'Nachingwea',
            'Ruangwa',
        ],
        'Manyara' => [
            'Babati Town',
            'Babati District',
            'Hanang',
            'Kiteto',
            'Mbulu',
            'Simanjiro',
        ],
        'Mara' => [
            'Musoma Municipal',
            'Musoma District',
            'Bunda',
            'Butiama',
            'Rorya',
            'Serengeti',
            'Tarime',
        ],
        'Mbeya' => [
            'Mbeya City',
            'Mbeya District',
            'Busokelo',
            'Chunya',
            'Kyela',
            'Mbarali',
            'Rungwe',
        ],
        'Morogoro' => [
            'Morogoro Municipal',
            'Morogoro District',
            'Gairo',
            'Kilombero',
            'Kilosa',
            'Malinyi',
            'Mvomero',
            'Ulanga',
        ],
        'Mtwara' => [
            'Mtwara Municipal',
            'Mtwara District',
            'Masasi Town',
            'Masasi District',
            'Nanyumbu',
            'Newala',
            'Tandahimba',
        ],
        'Mwanza' => [
            'Nyamagana',
            'Ilemela',
            'Kwimba',
            'Magu',
            'Misungwi',
            'Sengerema',
            'Ukerewe',
        ],
        'Njombe' => [
            'Njombe Town',
            'Njombe District',
            'Ludewa',
            'Makambako Town',
            'Makete',
            "Wanging'ombe",
        ],
        'Pemba North' => [
            'Micheweni',
            'Wete',
        ],
        'Pemba South' => [
            'Chake Chake',
            'Mkoani',
        ],
        'Pwani' => [
            'Kibaha Town',
            'Kibaha District',
            'Bagamoyo',
            'Kisarawe',
            'Mkuranga',
            'Rufiji',
        ],
        'Rukwa' => [
            'Sumbawanga Municipal',
            'Sumbawanga District',
            'Kalambo',
            'Nkasi',
        ],
        'Ruvuma' => [
            'Songea Municipal',
            'Songea District',
            'Mbinga Town',
            'Mbinga District',
            'Namtumbo',
            'Nyasa',
            'Tunduru',
        ],
        'Shinyanga' => [
            'Shinyanga Municipal',
            'Shinyanga District',
            'Kahama Town',
            'Kahama District',
            'Kishapu',
        ],
        'Simiyu' => [
            'Bariadi Town',
            'Bariadi District',
            'Busega',
            'Itilima',
            'Maswa',
            'Meatu',
        ],
        'Singida' => [
            'Singida Municipal',
            'Singida District',
            'Ikungi',
            'Iramba',
            'Itigi',
            'Manyoni',
            'Mkalama',
        ],
        'Songwe' => [
            'Songwe District',
            'Ileje',
            'Mbozi',
            'Momba',
            'Tunduma Town',
        ],
        'Tabora' => [
            'Tabora Municipal',
            'Urambo',
            'Uyui',
            'Igunga',
            'Kaliua',
            'Nzega Town',
            'Nzega District',
            'Sikonge',
        ],
        'Tanga' => [
            'Tanga City',
            'Handeni Town',
            'Handeni District',
            'Kilindi',
            'Korogwe Town',
            'Korogwe District',
            'Lushoto',
            'Mkinga',
            'Muheza',
            'Pangani',
        ],
        'Unguja North' => [
            'Kaskazini A',
            'Kaskazini B',
        ],
        'Unguja South' => [
            'Kati',
            'Kusini',
        ],
        'Unguja Urban/West' => [
            'Mjini',
            'Magharibi',
        ],
    ],
];
